In [1]:
import pandas as pd

In [2]:
df_spark = pd.read_csv('df_spark.csv')

In [3]:
df_spark.head()

Unnamed: 0    0     1     2    3    4     5    6    7      8    9   10   11
0           0  7.0  21.0  30.0  2.0  3.0  30.0  2.0  3.0   59.0  7.0  2.0  0.0
1           1  7.0  32.0  70.0  2.0  4.0  68.0  2.0  4.0  134.0  7.0  2.0  0.0
2           2  7.0  15.0   1.0  2.0  2.0   0.0  2.0  2.0    0.0  7.0  2.0  0.0
3           3  7.0  33.0  77.0  2.0  7.0  73.0  2.0  7.0  144.0  7.0  2.0  0.0
4           4  7.0  55.0  78.0  3.0  7.0  74.0  3.0  7.0  146.0  8.0  2.0  0.0

In [4]:
df_spark = df_spark.drop(columns="Unnamed: 0")

In [5]:
y = df_spark.iloc[:,0].values
X = df_spark.iloc[:,1:].values

In [6]:
import numpy as np
from xgboost import XGBClassifier
from sklearn.model_selection import learning_curve
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state = 1)

# 5-Fold Cross validation Estimation for XGBOOST

In [8]:
# Create a pipeline with StandardScaler and XGBoost classifier
pipe_xgb = Pipeline([('scl', StandardScaler()), ('clf', XGBClassifier())])

# Perform learning curve analysis
train_sizes_xgb, train_scores_xgb, test_scores_xgb = learning_curve(
    estimator=pipe_xgb,
    X=X_train, y=y_train,
    train_sizes=np.linspace(0.2, 1.0, 5),
    cv=5, n_jobs=-1
)

# Calculate mean and standard deviation of training and test scores
train_mean_xgb = np.mean(train_scores_xgb, axis=1)
train_std_xgb = np.std(train_scores_xgb, axis=1)
test_mean_xgb = np.mean(test_scores_xgb, axis=1)
test_std_xgb = np.std(test_scores_xgb, axis=1)

# Print the mean training scores
for score in train_mean_xgb:
    print(score)

# Print the mean test scores
for score in test_mean_xgb:
    print(score)

0.9943687794656888
0.9944822769338222
0.9944095221465572
0.9943513183167452
0.9942413382166133
0.9941784934920946
0.9942064308425861
0.9942238918695752
0.9942343685589414
0.9942378607887301


# Evaluation Metrics Calculations for XGBOOST

In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import numpy as np

# Assuming you have your X and y data prepared
# Replace X and y with your actual data

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

# Create a pipeline with StandardScaler and XGBoost classifier
pipe_xgb = Pipeline([('scl', StandardScaler()), ('clf', XGBClassifier())])

# Fit the pipeline on the training data
pipe_xgb.fit(X_train, y_train)

# Make predictions using your trained XGBoost model
y_pred = pipe_xgb.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision_micro = precision_score(y_test, y_pred, average='micro')
recall_micro = recall_score(y_test, y_pred, average='micro')
f1_micro = f1_score(y_test, y_pred, average='micro')
conf_matrix = confusion_matrix(y_test, y_pred)

# Print evaluation metrics
print("Accuracy:", accuracy)
print("Precision (Micro):", precision_micro)
print("Recall (Micro):", recall_micro)
print("F1-score (Micro):", f1_micro)
print("Confusion Matrix:")
print(conf_matrix)


Accuracy: 0.994119208258252
Precision (Micro): 0.994119208258252
Recall (Micro): 0.994119208258252
F1-score (Micro): 0.994119208258252
Confusion Matrix:
[[  775     0     0     0     0     0     0   403]
 [    0    63     0     0     0     0     0     0]
 [    0     0   169     0     0     0     0     0]
 [    0     0     0   155     0     0     0     0]
 [    0     0     0     0   305     0     0     0]
 [    0     0     0     0     0   120     0     0]
 [    0     0     0     0     0     0    28     0]
 [   18     0     0     0     0     0     0 69553]]
